name:

on:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Dependencies
        run: pip install httpx dataclass_wizard
      - name: Run script
        run: python scripts/fetch_apod.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
